# Generated by Django 2.1.3 on 2019-02-07 16:29

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('agentex', '0001_initial'), ('agentex', '0002_auto_20181122_1242'), ('agentex', '0003_auto_20181122_1443'), ('agentex', '0004_auto_20181122_1541'), ('agentex', '0005_auto_20181122_2117'), ('agentex', '0006_auto_20181127_1640'), ('agentex', '0007_auto_20181127_1649'), ('agentex', '0008_auto_20181130_1442'), ('agentex', '0009_auto_20190201_1448'), ('agentex', '0010_auto_20190207_1627')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tag', models.CharField(default='LCO', max_length=75)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('dataexploreview', models.BooleanField(default=True, verbose_name='use web interface for dataexplorer')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'observer',
                'db_table': 'observer',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'achievement unlocked',
                'verbose_name_plural': 'achievements unlocked',
                'db_table': 'dataexplorer_achievement',
            },
        ),
        migrations.CreateModel(
            name='AverageSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.TextField(blank=True, null=True)),
                ('settype', models.CharField(choices=[('S', 'Source'), ('C', 'Calibration'), ('B', 'Background'), ('R', 'Reduced'), ('F', 'Final'), ('E', 'Error bar')], max_length=1)),
            ],
            options={
                'verbose_name': 'combined lightcurve set',
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='code, no spaces', max_length=20)),
                ('description', models.CharField(help_text='brief, publicly readable', max_length=200)),
                ('image', models.CharField(choices=[('badge/badge_measurement_250.png', 'badge_measurement_250.png'), ('badge/badge_calibrators_15.png', 'badge_calibrators_15.png'), ('badge/badge_measurement_1000.png', 'badge_measurement_1000.png'), ('badge/badge_manual.png', 'badge_manual.png'), ('badge/badge_top_measurer.png', 'badge_top_measurer.png'), ('badge/badge_calibrators_10.png', 'badge_calibrators_10.png'), ('badge/badge_measurement_50.png', 'badge_measurement_50.png'), ('badge/badge_completed_1.png', 'badge_completed_1.png'), ('badge/badge_completed_2.png', 'badge_completed_2.png'), ('badge/badge_calibrators_3.png', 'badge_calibrators_3.png'), ('badge/badge_completed_3.png', 'badge_completed_3.png'), ('badge/badge_measurement_1500.png', 'badge_measurement_1500.png'), ('badge/badge_measurement_25.png', 'badge_measurement_25.png'), ('badge/badge_calibrators_5.png', 'badge_calibrators_5.png'), ('badge/badge_completed_4.png', 'badge_completed_4.png'), ('badge/badge_completed_5.png', 'badge_completed_5.png'), ('badge/badges.svg', 'badges.svg'), ('badge/badge_measurement_2000.png', 'badge_measurement_2000.png'), ('badge/badge_measurement_10.png', 'badge_measurement_10.png'), ('badge/badge_lightcurve_1star.png', 'badge_lightcurve_1star.png'), ('badge/badge_planet_1.png', 'badge_planet_1.png'), ('badge/badge_lightcurve_3star.png', 'badge_lightcurve_3star.png'), ('badge/badge_measurement_500.png', 'badge_measurement_500.png'), ('badge/badge_measurement_1.png', 'badge_measurement_1.png'), ('badge/badge_planet_3.png', 'badge_planet_3.png'), ('badge/badge_planet_2.png', 'badge_planet_2.png'), ('badge/badge_planet_6.png', 'badge_planet_6.png'), ('badge/badge_measurement_100.png', 'badge_measurement_100.png'), ('badge/badge_planet_7.png', 'badge_planet_7.png'), ('badge/badge_measurement_5.png', 'badge_measurement_5.png'), ('badge/badge_planet_5.png', 'badge_planet_5.png'), ('badge/badge_planet_4.png', 'badge_planet_4.png'), ('badge/badge_calibrators_25.png', 'badge_calibrators_25.png'), ('badge/badge_lightcurve_2star.png', 'badge_lightcurve_2star.png')], max_length=100)),
            ],
            options={
                'verbose_name': 'badge',
                'db_table': 'dataexplorer_badge',
            },
        ),
        migrations.CreateModel(
            name='CatSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='object name')),
                ('xpos', models.IntegerField(blank=True, verbose_name='x position on finder image')),
                ('ypos', models.IntegerField(blank=True, verbose_name='y position on finder image')),
                ('catalogue', models.CharField(max_length=20, verbose_name='catalogue name')),
                ('final', models.BooleanField(default=True, verbose_name='include in final curve')),
            ],
            options={
                'verbose_name': 'catalogue source',
                'db_table': 'dataexplorer_catsource',
            },
        ),
        migrations.CreateModel(
            name='DataCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('calid', models.IntegerField(verbose_name='calibrator order')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'data collection',
                'db_table': 'dataexplorer_datacollection',
            },
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(max_length=20)),
                ('taken', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('value', models.FloatField(blank=True, null=True)),
                ('pointtype', models.CharField(choices=[('S', 'Source'), ('C', 'Calibration'), ('B', 'Background'), ('R', 'Reduced'), ('F', 'Final'), ('E', 'Error bar')], max_length=1)),
                ('xpos', models.IntegerField(blank=True, verbose_name='x position')),
                ('ypos', models.IntegerField(blank=True, verbose_name='y position')),
                ('radius', models.IntegerField(blank=True, verbose_name='aperture radius')),
                ('entrymode', models.CharField(choices=[('W', 'Web'), ('M', 'Manual'), ('N', 'No javascript')], default='W', max_length=1)),
                ('offset', models.FloatField(blank=True, verbose_name='distance from source')),
                ('tstamp', models.IntegerField(blank=True, verbose_name='unix timestamp')),
                ('coorder', models.ForeignKey(blank=True, help_text='point order', null=True, on_delete=django.db.models.deletion.CASCADE, to='agentex.DataCollection')),
            ],
            options={
                'verbose_name': 'data point',
                'db_table': 'dataexplorer_datapoint',
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fits', models.URLField(blank=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('telescopeid', models.CharField(blank=True, max_length=100)),
                ('max_x', models.IntegerField(verbose_name='max pixels (x)')),
                ('max_y', models.IntegerField(verbose_name='max pixels (y)')),
            ],
            options={
                'verbose_name': 'data source image',
                'db_table': 'dataexplorer_datasource',
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('D', 'Dip'), ('N', 'No Dip'), ('O', 'Odd'), ('B', 'Blip'), ('P', 'Periodic'), ('S', 'Noise'), ('R', 'Other')], max_length=1, verbose_name='decision')),
                ('taken', models.DateTimeField(default=datetime.datetime.now)),
                ('current', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'lightcurve decision',
                'db_table': 'dataexplorer_decision',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='code, no spaces and no hyphens', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('start', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('end', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('midpoint', models.DateTimeField(blank=True, null=True)),
                ('numobs', models.IntegerField(blank=True, default=0, null=True)),
                ('finder', models.IntegerField(blank=True, default=1, verbose_name='id of finder chart source')),
                ('xpos', models.IntegerField(default=0, verbose_name='x pos on finder chart')),
                ('ypos', models.IntegerField(default=0, verbose_name='y pos on finder chart')),
                ('enabled', models.BooleanField(default=True, help_text='show this event on main site')),
                ('illustration', models.CharField(blank=True, choices=[('illustration/planet_OGLE-TR-132b.jpg', 'planet_OGLE-TR-132b.jpg'), ('illustration/Hat-P-25b-finder-thumb2.jpg', 'Hat-P-25b-finder-thumb2.jpg'), ('illustration/planet_HAT-P-8b.jpg', 'planet_HAT-P-8b.jpg'), ('illustration/planet_HAT-P-11b.jpg', 'planet_HAT-P-11b.jpg'), ('illustration/planet_WASP-2b.jpg', 'planet_WASP-2b.jpg'), ('illustration/planet_HAT-P-25b.jpg', 'planet_HAT-P-25b.jpg'), ('illustration/planet_Qatar-1-b.jpg', 'planet_Qatar-1-b.jpg'), ('illustration/planet_TrES-3-b.jpg', 'planet_TrES-3-b.jpg'), ('illustration/planet_CoRoT-2b.jpg', 'planet_CoRoT-2b.jpg'), ('illustration/planet_GJ1214b.jpg', 'planet_GJ1214b.jpg'), ('illustration/planet_wasp43-b.jpg', 'planet_wasp43-b.jpg')], help_text='illustration for this event', max_length=100, verbose_name='illustration')),
                ('radius', models.IntegerField(default=10, verbose_name='aperture radius')),
                ('ap', models.FloatField(blank=True, null=True, verbose_name='semi-major axis')),
                ('constellation', models.CharField(blank=True, max_length=100)),
                ('dec', models.CharField(blank=True, max_length=100, verbose_name='declination')),
                ('description', models.TextField(default='x')),
                ('etd_pl', models.URLField(blank=True, null=True, verbose_name='Exoplanet Transit Database: Planet')),
                ('exoplanet_enc_pl', models.URLField(blank=True, null=True, verbose_name='Exoplanet Encyclopaedia: Planet')),
                ('exoplanet_enc_st', models.URLField(blank=True, null=True, verbose_name='Exoplanet Encyclopaedia: Star')),
                ('finderchart', models.CharField(blank=True, choices=[('finderchart/OGLETR132b-finder.jpg', 'OGLETR132b-finder.jpg'), ('finderchart/corot2b.jpg', 'corot2b.jpg'), ('finderchart/QATAR1b-finder.jpg', 'QATAR1b-finder.jpg'), ('finderchart/Hat-P-25b-finder.jpg', 'Hat-P-25b-finder.jpg'), ('finderchart/Wasp2b-finder.jpg', 'Wasp2b-finder.jpg'), ('finderchart/TrES3b-finder.jpg', 'TrES3b-finder.jpg'), ('finderchart/Hat-P-8b-finder.jpg', 'Hat-P-8b-finder.jpg'), ('finderchart/Wasp43b-finder.jpg', 'Wasp43b-finder.jpg')], help_text='Image with a clearly marked up target position', max_length=100, verbose_name='Finder chart')),
                ('finderchart_tb', models.CharField(blank=True, choices=[('finderchart/thumb/TrES3b-finder-thumb2.jpg', 'TrES3b-finder-thumb2.jpg'), ('finderchart/thumb/Hat-P-25b-finder-thumb2.jpg', 'Hat-P-25b-finder-thumb2.jpg'), ('finderchart/thumb/corot2b-finder.thumb.jpg', 'corot2b-finder.thumb.jpg'), ('finderchart/thumb/Hat-P-8b-finder-thumb2.jpg', 'Hat-P-8b-finder-thumb2.jpg'), ('finderchart/thumb/Wasp2b-finder-thumb2.jpg', 'Wasp2b-finder-thumb2.jpg'), ('finderchart/thumb/OGLETR132b-finder-thumb2.jpg', 'OGLETR132b-finder-thumb2.jpg'), ('finderchart/thumb/corot2b-finder.thumb.lg.jpg', 'corot2b-finder.thumb.lg.jpg'), ('finderchart/thumb/QATAR1b-finder-thumb2.jpg', 'QATAR1b-finder-thumb2.jpg'), ('finderchart/thumb/Wasp43b-finder-thumb.jpg', 'Wasp43b-finder-thumb.jpg')], help_text='Image with a clearly marked up target position', max_length=100, verbose_name='Finder chart thumbnail')),
                ('inclination', models.FloatField(blank=True, null=True, verbose_name='inclination of planet orbit')),
                ('magv', models.CharField(blank=True, max_length=100, verbose_name='apparent magnitude V')),
                ('mass', models.FloatField(blank=True, null=True, verbose_name='mass of host star')),
                ('period', models.FloatField(blank=True, null=True, verbose_name='period of planet orbit (days)')),
                ('ra', models.CharField(blank=True, max_length=100, verbose_name='right ascension')),
                ('rstar', models.FloatField(blank=True, null=True, verbose_name='radius of host star')),
                ('simbad_pl', models.URLField(blank=True, null=True, verbose_name='Simbad: Planet')),
                ('simbad_st', models.URLField(blank=True, null=True, verbose_name='Simbad: Star')),
                ('data_download', models.URLField(blank=True, null=True, verbose_name='Download full dataset')),
                ('download_size', models.FloatField(blank=True, null=True, verbose_name='How big in Mb is the download')),
            ],
            options={
                'verbose_name': 'transit event',
                'db_table': 'dataexplorer_event',
            },
        ),
        migrations.AddField(
            model_name='decision',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.Event'),
        ),
        migrations.AddField(
            model_name='decision',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.CatSource'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.Event'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.DataSource'),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.Event'),
        ),
        migrations.AddField(
            model_name='datacollection',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentex.CatSource'),
        ),
        migrations.AddField(
            model_name='catsource',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.DataSource'),
        ),
        migrations.AddField(
            model_name='averageset',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.Event'),
        ),
        migrations.AddField(
            model_name='averageset',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agentex.CatSource'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='badge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agentex.Badge'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='achievement',
            name='planet',
            field=models.ForeignKey(blank=True, help_text='planet', null=True, on_delete=django.db.models.deletion.CASCADE, to='agentex.Event'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='fits',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='image',
            field=models.CharField(blank=True, choices=[('images/planets/l_e_20090603_64_312_1_1.jpg', 'l_e_20090603_64_312_1_1.jpg'), ('images/planets/l_e_20090603_64_379_1_1.jpg', 'l_e_20090603_64_379_1_1.jpg'), ('images/planets/l_e_20090603_64_409_1_1.jpg', 'l_e_20090603_64_409_1_1.jpg'), ('images/planets/l_e_20090603_64_286_1_1.jpg', 'l_e_20090603_64_286_1_1.jpg'), ('images/planets/l_e_20090603_64_212_1_1.jpg', 'l_e_20090603_64_212_1_1.jpg'), ('images/planets/l_e_20090603_64_129_1_1.jpg', 'l_e_20090603_64_129_1_1.jpg'), ('images/planets/l_e_20090603_64_348_1_1.jpg', 'l_e_20090603_64_348_1_1.jpg'), ('images/planets/l_e_20090603_64_46_1_1.jpg', 'l_e_20090603_64_46_1_1.jpg'), ('images/planets/l_e_20090603_64_251_1_1.jpg', 'l_e_20090603_64_251_1_1.jpg'), ('images/planets/l_e_20090603_64_96_1_1.jpg', 'l_e_20090603_64_96_1_1.jpg'), ('images/planets/l_e_20090603_64_18_1_1.jpg', 'l_e_20090603_64_18_1_1.jpg'), ('images/planets/l_e_20090603_64_186_1_1.jpg', 'l_e_20090603_64_186_1_1.jpg'), ('images/planets/l_e_20090603_64_172_1_1.jpg', 'l_e_20090603_64_172_1_1.jpg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='image',
            field=models.CharField(blank=True, choices=[('images/planets/.DS_Store', '.DS_Store'), ('images/planets/l_e_20090603_64_129_1_1.jpg', 'l_e_20090603_64_129_1_1.jpg'), ('images/planets/l_e_20090603_64_172_1_1.jpg', 'l_e_20090603_64_172_1_1.jpg'), ('images/planets/l_e_20090603_64_186_1_1.jpg', 'l_e_20090603_64_186_1_1.jpg'), ('images/planets/l_e_20090603_64_18_1_1.jpg', 'l_e_20090603_64_18_1_1.jpg'), ('images/planets/l_e_20090603_64_212_1_1.jpg', 'l_e_20090603_64_212_1_1.jpg'), ('images/planets/l_e_20090603_64_251_1_1.jpg', 'l_e_20090603_64_251_1_1.jpg'), ('images/planets/l_e_20090603_64_286_1_1.jpg', 'l_e_20090603_64_286_1_1.jpg'), ('images/planets/l_e_20090603_64_312_1_1.jpg', 'l_e_20090603_64_312_1_1.jpg'), ('images/planets/l_e_20090603_64_348_1_1.jpg', 'l_e_20090603_64_348_1_1.jpg'), ('images/planets/l_e_20090603_64_379_1_1.jpg', 'l_e_20090603_64_379_1_1.jpg'), ('images/planets/l_e_20090603_64_409_1_1.jpg', 'l_e_20090603_64_409_1_1.jpg'), ('images/planets/l_e_20090603_64_46_1_1.jpg', 'l_e_20090603_64_46_1_1.jpg'), ('images/planets/l_e_20090603_64_96_1_1.jpg', 'l_e_20090603_64_96_1_1.jpg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='averageset',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
