# Generated by Django 2.1.3 on 2018-11-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='fits',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
