# Generated by Django 2.1.8 on 2019-05-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentex', '0003_auto_20190510_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data_download',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
