# Generated by Django 2.1.3 on 2018-11-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentex', '0005_auto_20181122_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='event',
            name='ap',
            field=models.FloatField(blank=True, null=True, verbose_name='semi-major axis'),
        ),
        migrations.AddField(
            model_name='event',
            name='constellation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='dec',
            field=models.CharField(blank=True, max_length=100, verbose_name='declination'),
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='x'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='etd_pl',
            field=models.URLField(blank=True, null=True, verbose_name='Exoplanet Transit Database: Planet'),
        ),
        migrations.AddField(
            model_name='event',
            name='exoplanet_enc_pl',
            field=models.URLField(blank=True, null=True, verbose_name='Exoplanet Encyclopaedia: Planet'),
        ),
        migrations.AddField(
            model_name='event',
            name='exoplanet_enc_st',
            field=models.URLField(blank=True, null=True, verbose_name='Exoplanet Encyclopaedia: Star'),
        ),
        migrations.AddField(
            model_name='event',
            name='finderchart',
            field=models.CharField(blank=True, choices=[('finderchart/.DS_Store', '.DS_Store'), ('finderchart/corot2b.jpg', 'corot2b.jpg'), ('finderchart/Hat-P-25b-finder.jpg', 'Hat-P-25b-finder.jpg'), ('finderchart/Hat-P-8b-finder.jpg', 'Hat-P-8b-finder.jpg'), ('finderchart/OGLETR132b-finder.jpg', 'OGLETR132b-finder.jpg'), ('finderchart/QATAR1b-finder.jpg', 'QATAR1b-finder.jpg'), ('finderchart/TrES3b-finder.jpg', 'TrES3b-finder.jpg'), ('finderchart/Wasp2b-finder.jpg', 'Wasp2b-finder.jpg')], help_text='Image with a clearly marked up target position', max_length=100, verbose_name='Finder chart'),
        ),
        migrations.AddField(
            model_name='event',
            name='finderchart_tb',
            field=models.CharField(blank=True, choices=[('finderchart/thumb/corot2b-finder.thumb.jpg', 'corot2b-finder.thumb.jpg'), ('finderchart/thumb/corot2b-finder.thumb.lg.jpg', 'corot2b-finder.thumb.lg.jpg'), ('finderchart/thumb/Hat-P-25b-finder-thumb2.jpg', 'Hat-P-25b-finder-thumb2.jpg'), ('finderchart/thumb/Hat-P-8b-finder-thumb2.jpg', 'Hat-P-8b-finder-thumb2.jpg'), ('finderchart/thumb/OGLETR132b-finder-thumb2.jpg', 'OGLETR132b-finder-thumb2.jpg'), ('finderchart/thumb/QATAR1b-finder-thumb2.jpg', 'QATAR1b-finder-thumb2.jpg'), ('finderchart/thumb/TrES3b-finder-thumb2.jpg', 'TrES3b-finder-thumb2.jpg'), ('finderchart/thumb/Wasp2b-finder-thumb2.jpg', 'Wasp2b-finder-thumb2.jpg')], help_text='Image with a clearly marked up target position', max_length=100, verbose_name='Finder chart thumbnail'),
        ),
        migrations.AddField(
            model_name='event',
            name='inclination',
            field=models.FloatField(blank=True, null=True, verbose_name='inclination of planet orbit'),
        ),
        migrations.AddField(
            model_name='event',
            name='magv',
            field=models.CharField(blank=True, max_length=100, verbose_name='apparent magnitude V'),
        ),
        migrations.AddField(
            model_name='event',
            name='mass',
            field=models.FloatField(blank=True, null=True, verbose_name='mass of host star'),
        ),
        migrations.AddField(
            model_name='event',
            name='period',
            field=models.FloatField(blank=True, null=True, verbose_name='period of planet orbit (days)'),
        ),
        migrations.AddField(
            model_name='event',
            name='ra',
            field=models.CharField(blank=True, max_length=100, verbose_name='right ascension'),
        ),
        migrations.AddField(
            model_name='event',
            name='rstar',
            field=models.FloatField(blank=True, null=True, verbose_name='radius of host star'),
        ),
        migrations.AddField(
            model_name='event',
            name='simbad_pl',
            field=models.URLField(blank=True, null=True, verbose_name='Simbad: Planet'),
        ),
        migrations.AddField(
            model_name='event',
            name='simbad_st',
            field=models.URLField(blank=True, null=True, verbose_name='Simbad: Star'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='image',
            field=models.CharField(choices=[('badge/badge_calibrators_10.png', 'badge_calibrators_10.png'), ('badge/badge_calibrators_15.png', 'badge_calibrators_15.png'), ('badge/badge_calibrators_25.png', 'badge_calibrators_25.png'), ('badge/badge_calibrators_3.png', 'badge_calibrators_3.png'), ('badge/badge_calibrators_5.png', 'badge_calibrators_5.png'), ('badge/badge_completed_1.png', 'badge_completed_1.png'), ('badge/badge_completed_2.png', 'badge_completed_2.png'), ('badge/badge_completed_3.png', 'badge_completed_3.png'), ('badge/badge_completed_4.png', 'badge_completed_4.png'), ('badge/badge_completed_5.png', 'badge_completed_5.png'), ('badge/badge_lightcurve_1star.png', 'badge_lightcurve_1star.png'), ('badge/badge_lightcurve_2star.png', 'badge_lightcurve_2star.png'), ('badge/badge_lightcurve_3star.png', 'badge_lightcurve_3star.png'), ('badge/badge_manual.png', 'badge_manual.png'), ('badge/badge_measurement_1.png', 'badge_measurement_1.png'), ('badge/badge_measurement_10.png', 'badge_measurement_10.png'), ('badge/badge_measurement_100.png', 'badge_measurement_100.png'), ('badge/badge_measurement_1000.png', 'badge_measurement_1000.png'), ('badge/badge_measurement_1500.png', 'badge_measurement_1500.png'), ('badge/badge_measurement_2000.png', 'badge_measurement_2000.png'), ('badge/badge_measurement_25.png', 'badge_measurement_25.png'), ('badge/badge_measurement_250.png', 'badge_measurement_250.png'), ('badge/badge_measurement_5.png', 'badge_measurement_5.png'), ('badge/badge_measurement_50.png', 'badge_measurement_50.png'), ('badge/badge_measurement_500.png', 'badge_measurement_500.png'), ('badge/badge_planet_1.png', 'badge_planet_1.png'), ('badge/badge_planet_2.png', 'badge_planet_2.png'), ('badge/badge_planet_3.png', 'badge_planet_3.png'), ('badge/badge_planet_4.png', 'badge_planet_4.png'), ('badge/badge_planet_5.png', 'badge_planet_5.png'), ('badge/badge_planet_6.png', 'badge_planet_6.png'), ('badge/badge_planet_7.png', 'badge_planet_7.png'), ('badge/badge_top_measurer.png', 'badge_top_measurer.png'), ('badge/badges.svg', 'badges.svg')], max_length=100),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='image',
            field=models.CharField(blank=True, choices=[('images/planets/.DS_Store', '.DS_Store'), ('images/planets/l_e_20090603_64_129_1_1.jpg', 'l_e_20090603_64_129_1_1.jpg'), ('images/planets/l_e_20090603_64_172_1_1.jpg', 'l_e_20090603_64_172_1_1.jpg'), ('images/planets/l_e_20090603_64_186_1_1.jpg', 'l_e_20090603_64_186_1_1.jpg'), ('images/planets/l_e_20090603_64_18_1_1.jpg', 'l_e_20090603_64_18_1_1.jpg'), ('images/planets/l_e_20090603_64_212_1_1.jpg', 'l_e_20090603_64_212_1_1.jpg'), ('images/planets/l_e_20090603_64_251_1_1.jpg', 'l_e_20090603_64_251_1_1.jpg'), ('images/planets/l_e_20090603_64_286_1_1.jpg', 'l_e_20090603_64_286_1_1.jpg'), ('images/planets/l_e_20090603_64_312_1_1.jpg', 'l_e_20090603_64_312_1_1.jpg'), ('images/planets/l_e_20090603_64_348_1_1.jpg', 'l_e_20090603_64_348_1_1.jpg'), ('images/planets/l_e_20090603_64_379_1_1.jpg', 'l_e_20090603_64_379_1_1.jpg'), ('images/planets/l_e_20090603_64_409_1_1.jpg', 'l_e_20090603_64_409_1_1.jpg'), ('images/planets/l_e_20090603_64_46_1_1.jpg', 'l_e_20090603_64_46_1_1.jpg'), ('images/planets/l_e_20090603_64_96_1_1.jpg', 'l_e_20090603_64_96_1_1.jpg')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='finder',
            field=models.IntegerField(blank=True, default=1, verbose_name='id of finder chart source'),
        ),
        migrations.AlterField(
            model_name='event',
            name='illustration',
            field=models.CharField(blank=True, choices=[('illustration/Hat-P-25b-finder-thumb2.jpg', 'Hat-P-25b-finder-thumb2.jpg'), ('illustration/planet_CoRoT-2b.jpg', 'planet_CoRoT-2b.jpg'), ('illustration/planet_GJ1214b.jpg', 'planet_GJ1214b.jpg'), ('illustration/planet_HAT-P-11b.jpg', 'planet_HAT-P-11b.jpg'), ('illustration/planet_HAT-P-25b.jpg', 'planet_HAT-P-25b.jpg'), ('illustration/planet_HAT-P-8b.jpg', 'planet_HAT-P-8b.jpg'), ('illustration/planet_OGLE-TR-132b.jpg', 'planet_OGLE-TR-132b.jpg'), ('illustration/planet_Qatar-1-b.jpg', 'planet_Qatar-1-b.jpg'), ('illustration/planet_TrES-3-b.jpg', 'planet_TrES-3-b.jpg'), ('illustration/planet_WASP-2b.jpg', 'planet_WASP-2b.jpg')], help_text='illustration for this event', max_length=100, verbose_name='illustration'),
        ),
        migrations.AlterField(
            model_name='target',
            name='finderchart',
            field=models.FileField(blank=True, help_text='Image with a clearly marked up target position', upload_to='finderchart', verbose_name='Finder chart'),
        ),
        migrations.AlterField(
            model_name='target',
            name='finderchart_tb',
            field=models.FileField(blank=True, help_text='Image with a clearly marked up target position', upload_to='finderchart/thumb', verbose_name='Finder chart thumbnail'),
        ),
    ]
