# Generated by Django 2.1.3 on 2018-11-27 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agentex', '0006_auto_20181127_1640'),
    ]

    operations = [

        migrations.RemoveField(
            model_name='datasource',
            name='target',
        ),
        migrations.DeleteModel(
            name='Target',
        ),

    ]
