# Generated by Django 2.1.3 on 2019-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agentex', '0009_auto_20190201_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='data_download',
            field=models.URLField(blank=True, null=True, verbose_name='Download full dataset'),
        ),
        migrations.AddField(
            model_name='event',
            name='download_size',
            field=models.FloatField(blank=True, null=True, verbose_name='How big in Mb is the download'),
        ),
    ]
