#!/bin/bash

# substitute the prefix into the nginx configuration
echo "Running with PREFIX=${PREFIX}"
sed -i -e "s:@PREFIX@:${PREFIX}:g" /etc/nginx/nginx.conf

# if any schema changed have happened but not been applied
python /var/www/apps/agentexoplanet/manage.py migrate --noinput

# collect static files
python /var/www/apps/agentexoplanet/manage.py collectstatic --noinput

# Run under supervisord
exec /usr/bin/supervisord -n -c /etc/supervisord.conf
